steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/yarrabotula/cicd-service.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/brilliant-scene-290913/venkatjob:latest','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/brilliant-scene-290913/venkatjob:latest']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/hello-world-service'
  - 'hello-world-service=gcr.io/brilliant-scene-290913/venkatjob:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kubernetesproject'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: brilliant-scene-290913
    _ZONE: europe-west2-a
    _GKE_CLUSTER: kubernetesproject
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: hello-world-service
    _CONTAINERNAME: hello-world-service    
    _REPO_NAME: cicd-service
    
    # Developers ONLY change
    _VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'

