steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/yarrabotula/cicd-service.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/bristol-302417/hello-GKE:latest','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/bristol-302417/hello-GKE:latest']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'

  args:
  - delete  
  - deployment
  - hello-GKE
  - --ignore-not-found
  env:
  - CLOUDSDK_COMPUTE_ZONE=europe-west2-c
  - CLOUDSDK_CONTAINER_CLUSTER=kubernetes
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - run
  - hello-GKE
  - --image=gcr.io/bristol-302417/hello-GKE
  env:
  - CLOUDSDK_COMPUTE_ZONE=europe-west2-c
  - CLOUDSDK_CONTAINER_CLUSTER=kubernetes
  


